POST_CREATED_MSG = "Post Created By {}"
POST_DELETED_MSG = "Post Deleted Successfully!"
LIKES_COUNT_MSG = "Likes for the post are:{}"
PERMISSION_DENIED_MSG = "you do not have permission to do this action"
LIKED_MSG = "Post Liked By {}"
ALREADY_LIKED_MSG = "you have already Liked this post"